[functions.get-location-from-coords]
enabled = true
verify_jwt = true
import_map = "./functions/get-location-from-coords/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-location-from-coords/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-location-from-coords/*.html" ]
[functions.get-weather-by-coords]
enabled = true
verify_jwt = true
import_map = "./functions/get-weather-by-coords/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-weather-by-coords/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-weather-by-coords/*.html" ]

[functions.get-coords-from-location]
enabled = true
verify_jwt = true
import_map = "./functions/get-coords-from-location/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-coords-from-location/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-coords-from-location/*.html" ]
